version: '3.7'
services:
  socat:
    image: alpine/socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - discovery
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=false"
 
  dnsmasq:
    image: jpillora/dnsmasq
    deploy:
      # Deploy the service to all nodes that match our constraints
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:dns.${HOST_DOMAIN}"
        - "traefik.port=8080"
        - "traefik.backend=dns"
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
    networks: 
      - discovery
    volumes:
      - ./opt/dnsmasq.conf:/etc/dnsmasq.conf

  consul:
    image: consul:1.5.3
    command: "consul agent -server -bind=${HOST_IP} -client=0.0.0.0 -ui -bootstrap-expect=1 -recursor=8.8.8.8 -node=master -data-dir=/consul/data"
    volumes:
      - consul-data:/consul/data
    environment:
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true, "datacenter": "infra"}'

    ports: 
      - "8600:8600/udp"
    networks:
      - discovery
    deploy:
      mode: global
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:consul.${HOST_DOMAIN}"
      - "traefik.port=8500"
      - "traefik.backend=consul"
      - "traefik.network=discovery"
      - "traefik.tags=${TRAEFIK_PUBLIC_TAG}"

  consul_replica:
    image: consul:1.5.3
    command: "consul agent -server -bind=${HOST_IP} -client=0.0.0.0 -retry-join=consul -data-dir=/consul/data"
    volumes:
      - consul-data-replica:/consul/data
    environment:
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - discovery 
    depends_on:
      - consul
    deploy:
      replicas: ${CONSUL_REPLICAS:-3}
      placement:
        preferences:
          - spread: node.id
    labels:
      - "traefik.enable=false"

  registrator:
    networks:
      - discovery
    depends_on:
      - consul
    image: gliderlabs/registrator
    command: -internal consul://consul:8500
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    labels:
      - "traefik.enable=false"

  traefik:
    image: traefik
    networks:
      - discovery
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    volumes:
      - "treafik_data:/tmp"
      - "./certs/:/certs/"
      - "./traefik/conf/traefik.toml:/traefik.toml"
    deploy:
      # Deploy the service to all nodes that match our constraints
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:${TRAEFIK_HOST}"
        - "traefik.port=8080"
        - "traefik.backend=traefik"

  portainer-agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer-agent_network
    deploy:
      mode: global
    labels:
      - "traefik.enable=false"

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify
    volumes:
      - "portainer_data:/data"
    networks:
      - portainer-agent_network
      - discovery
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:${PORTAINER_HOST}"
        - "traefik.port=9000"
        - "traefik.backend=portainer"

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - "./prometheus/:/etc/prometheus/"
      - "prometheus-data:/prometheus"
    networks:
      - discovery
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 2048M
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:${PROMETHEUS_HOST}"
        - "traefik.port=9090"
        - "traefik.backend=prometheus"

  grafana:
    image: grafana/grafana:6.2.5
    depends_on:
      - prometheus
    volumes:
      - "grafana-data:/var/lib/grafana"
      - ${PWD}/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - "GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}"
      - "GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}"
      - "GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}"
      - "GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}"
    networks:
      - discovery
    # user: "472" # Grafana container using bind mounts
    deploy:     
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:${GRAFANA_HOST}"
        - "traefik.port=3000"
        - "traefik.backend=grafana"

networks:
  portainer-agent_network:
    driver: overlay
  discovery:
    name: discovery
    driver: overlay
    attachable: true
volumes:
  treafik_data: {}
  portainer_data: {}
  prometheus-data: {}
  grafana-data: {}
  consul-data: {}
  consul-data-replica: {}
